sudo: required
dist: xenial
group: deprecated-2017Q4
branches:
  only:
  - staging
  - master
language: ruby
cache: bundler
services:
  - postgresql
  - redis-server
  - docker
addons:
  postgresql: "9.6"
env:
    global:
    - PATH=$PATH:$HOME/google-cloud-sdk/bin
    - PROJECT_ID="copper-mender-240813"
    - ZONE="us-central1-a"
    - IMAGE_NAME=bc_shipping
    - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/scripts/travis-ci-role.json"

before_install:
  - wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
  - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
  - gem update --system
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  - sudo apt-get -qq update
  - sudo apt-get install -y google-cloud-sdk kubectl
  - echo "${GCP_SERVICE_ACCOUNT}" | base64 -d > ${GOOGLE_APPLICATION_CREDENTIALS}
  - source /home/travis/.bashrc
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./scripts/sdk-configure.sh; fi'      

before_script:  
  - ./scripts/build-docker.sh || travis_terminate 1  

script: 
  - ./scripts/helm_deploy.sh || travis_terminate 1  