{{/* some vars to make life easier */}}
{{- $chartName := .Chart.Name }}
{{- $chartVersion := .Chart.Version | replace "+" "_" }}
{{- $chartFullName := printf "%s-%s" $chartName $chartVersion | replace "+" "_" }}
{{- $releaseName := .Release.Name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.schedule.name }}
  labels:
    app.kubernetes.io/component: bc-shipping-cron
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    helm.sh/chart: {{ $chartFullName }}
spec:
  replicas: {{ default 1 .Values.schedule.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: bc-shipping-cron
  template:
    metadata:
      labels:
        app.kubernetes.io/component: bc-shipping-cron
        app.kubernetes.io/instance: {{ $releaseName }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ .Values.appName }}
        helm.sh/chart: {{ $chartFullName }}
    spec:
      containers:
      - name: {{ .Values.schedule.name }}
        image: "{{ .Values.imageRepo }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        tty: true
        stdin: true
        command: ["/bin/sh", "-c"]
        args:
          - |
            {{ .Values.schedule.command }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configMapName }}
        resources:
          requests:
            memory: {{ .Values.schedule.memoryRequest | quote }}
            cpu: {{ .Values.schedule.cpuRequest | quote }}
          limits:
            memory: {{ .Values.schedule.memoryLimit | quote }}
            cpu: {{ .Values.schedule.cpuLimit | quote }}
        volumeMounts:
        - name: envs
          mountPath: /shipping/.envs
          subPath: .envs
        ports:
          - name: puma1
            containerPort: {{ default 9494 .Values.puma.containerPort1 }}
            protocol: TCP
          - name: puma2
            containerPort: {{ default 9422 .Values.puma.containerPort2 }}
            protocol: TCP
      volumes:
        - name: envs
          configMap:
            name: shipping-cron-envs
