{{- $chartName := .Chart.Name }}
{{- $chartVersion := .Chart.Version | replace "+" "_" }}
{{- $chartFullName := printf "%s-%s" $chartName $chartVersion | replace "+" "_" }}
{{- $releaseName := .Release.Name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Values.puma.name $releaseName }}
  labels:
    app.kubernetes.io/component: bc-shipping
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    helm.sh/chart: {{ $chartFullName }}
spec:
  replicas: {{ .Values.puma.replicaCount | default 1}}
  selector:
    matchLabels:
      app.kubernetes.io/component: bc-shipping
  template:
    metadata:
      labels:
        app.kubernetes.io/component: bc-shipping
        app.kubernetes.io/instance: {{ $releaseName }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ .Values.appName }}
        helm.sh/chart: {{ $chartFullName }}
    spec:
      containers:
      - name: {{ .Values.puma.name }}
        image: "{{ .Values.imageRepo }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.puma.containerPort1 }}
          initialDelaySeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.puma.containerPort1 }}
          initialDelaySeconds: 30
          timeoutSeconds: 3
        tty: true
        stdin: true
        command: ["/bin/sh", "-c"]
        args:
          - |
            {{ .Values.puma.command }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configMapName }}
        {{- with .Values.puma.resources }}
        resources:
          requests:
            memory: {{ .memoryRequest | quote }}
            cpu: {{ .cpuRequest | quote }}
          limits:
            memory: {{ .memoryLimit | quote }}
            cpu: {{ .cpuLimit | quote }}
        {{- end }}
        ports:
          - name: puma1
            containerPort: {{ default 9494 .Values.puma.containerPort1 }}
            protocol: TCP
          - name: puma2
            containerPort: {{ default 9422 .Values.puma.containerPort2 }}
            protocol: TCP