appName: bc_shipping

imageRepo: gcr.io/copper-mender-240813/bc_shipping
imageTag: staging-latest
imagePullPolicy: Always

serviceName: cluster-ip
serviceType: ClusterIP
servicePort: 9494

configMapName: bc-shipping

schedule:
    name: bytestand-cronjob
    command: bundle exec whenever --update-crontab && cron -f
    replicaCount: 1
    memoryRequest: 256Mi
    memoryLimit: 1024Mi
    cpuRequest: 50m
    cpuLimit: 150m

puma:
  name: shipping
  replicaCount: 1
  containerPort1: 9494
  containerPort2: 9422
  command: bundle exec puma -C config/puma/aws-production.rb
  resources:
    memoryRequest: 120Mi
    memoryLimit: 200Mi
    cpuRequest: 50m
    cpuLimit: 150m
